### ISSUE TITLE
file renaming often leads to crashes

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/broccoli-typescript-compiler#26]
I'll try to come up with something reproducible in the next few days.

**Comment by krisselden** [comment]
I suspect it has to do with this https://github.com/Microsoft/TypeScript/blob/master/src/compiler/tsc.ts#L517

Likely we should either try to match tsc's caching or removing parsed source file caching.  Or limit it to strictly file change.

Do you have a stack trace?

**Comment by stefanpenner** [comment]
> Do you have a stack trace?

Will provide one when i have a chance.

**Comment by runspired** [comment]
I hit this often, would be nice not to need to reboot the server all the time.

**Comment by krisselden** [comment]
@runspired I'd welcome a PR to align it with tsc behavior or a test or just remove the sourcefile cache, not sure when I can get a chance to fix.  The tests in the project are super annoying

**Comment by stefanpenner** [comment]
one related stack:

```
The Broccoli Plugin: [BroccoliMergeTrees: TypeScript passthrough + ouput] failed with:
Error: ENOENT: no such file or directory, symlink '/Users/spenner/src/stefanpenner/es6-promise/tmp/broccoli_merge_trees-input_base_path-PYsSvkQw.tmp/1/es6-promise' -> '/Users/spenner/src/stefanpenner/es6-pr
omise/tmp/broccoli_merge_trees-output_path-WiZdFly1.tmp/es6-promise'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at symlink (/Users/spenner/src/stefanpenner/es6-promise/node_modules/symlink-or-copy/index.js:79:14)
    at symlinkOrCopySync (/Users/spenner/src/stefanpenner/es6-promise/node_modules/symlink-or-copy/index.js:55:5)
    at BroccoliMergeTrees._applyMkdir (/Users/spenner/src/stefanpenner/es6-promise/node_modules/broccoli-merge-trees/index.js:149:12)
    at BroccoliMergeTrees.<anonymous> (/Users/spenner/src/stefanpenner/es6-promise/node_modules/broccoli-merge-trees/index.js:125:21)
    at Array.forEach (native)
    at BroccoliMergeTrees._applyPatch (/Users/spenner/src/stefanpenner/es6-promise/node_modules/broccoli-merge-trees/index.js:114:9)
    at BroccoliMergeTrees.build (/Users/spenner/src/stefanpenner/es6-promise/node_modules/broccoli-merge-trees/index.js:101:10)
    at /Users/spenner/src/stefanpenner/es6-promise/node_modules/broccoli-plugin/read_compat.js:61:34

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/Users/spenner/src/stefanpenner/es6-promise/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/spenner/src/stefanpenner/es6-promise/node_modules/broccoli-merge-trees/index.js:42:10)
    at new filter (/Users/spenner/src/stefanpenner/es6-promise/node_modules/broccoli-typescript-compiler/index.js:16:10)
    at Object.<anonymous> (/Users/spenner/src/stefanpenner/es6-promise/Brocfile.js:5:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

**Comment by krisselden** [comment]
That looks like you are importing something not in your input node.

**Comment by krisselden** [comment]
Nevermind looks like an issue with merge afterward

**Comment by krisselden** [comment]
For what it's worth the path you are using is for legacy compat with filter, only use it if you need stuff to pass through.  It also does not support things the main path does.  Use the named exports to get the behavior where you only get the program output

**Comment by stefanpenner** [comment]
@krisselden im not sure what that means.

this is how i am invoking this lib:

``` js
var es = new TypeScript('lib',{
  tsconfig: {
    compilerOptions: {
      module: "es2015"
    }
  }
});
```

**Comment by krisselden** [comment]
Ok, how did you require it? I have bad internet where I'm at, but look at the index.d.ts in the root and suggestions welcome, I tried to make clear in the readme but it seems like this is an issue with merge trees which is used to mimic the filter style. I was trying to make the default behavior close to the existing but now I'm regretting it, I suspect this has nothing todo with the actual plugin and is a bug in broccoli-merge-trees

**Comment by stefanpenner** [comment]
> I suspect this has nothing todo with the actual plugin and is a bug in broccoli-merge-trees

seems strange to only hit that bug, with this plugin. But i assume its possible

**Comment by stefanpenner** [comment]
> I suspect this has nothing todo with the actual plugin and is a bug in broccoli-merge-trees
> seems strange to only hit that bug, with this plugin. But i assume its possible

and if so, then it should be a good test case for merge-trees. Will investigate once i finish my current thing.

**Comment by runspired** [comment]
@stefanpenner I hit this often when developing ember apps without typescript, to be honest I mistook the repo for broccoli-merge-trees when I saw the issue pop up in my feed because of what the issue is.

**Comment by stefanpenner** [comment]
strange, i've only seen: https://github.com/broccolijs/broccoli-merge-trees/issues/50 outside of this repo.

**Comment by stefanpenner** [comment]
ya i think:  broccolijs/broccoli-merge-trees#50 is the cause
